// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl89shjKde1qyGZIEtt2BEz0ovtmly9CY',
    appId: '1:411595408555:web:2515a1e8edf7710215e3ee',
    messagingSenderId: '411595408555',
    projectId: 'ustagram-2f50c',
    authDomain: 'ustagram-2f50c.firebaseapp.com',
    storageBucket: 'ustagram-2f50c.firebasestorage.app',
    measurementId: 'G-1GVH8DS168',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHDAu6NArWtmYtbtdLieLolxOTs3ZAxM',
    appId: '1:411595408555:android:c4f64df1da92366315e3ee',
    messagingSenderId: '411595408555',
    projectId: 'ustagram-2f50c',
    storageBucket: 'ustagram-2f50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBpLZp3vj4TMjDMshz6WuS9M-DyuIy0o',
    appId: '1:411595408555:ios:0f97277a0d66a4de15e3ee',
    messagingSenderId: '411595408555',
    projectId: 'ustagram-2f50c',
    storageBucket: 'ustagram-2f50c.firebasestorage.app',
    iosClientId: '411595408555-v85hhidf3o4idjgq7kfu4vic3c27bpnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDBpLZp3vj4TMjDMshz6WuS9M-DyuIy0o',
    appId: '1:411595408555:ios:0f97277a0d66a4de15e3ee',
    messagingSenderId: '411595408555',
    projectId: 'ustagram-2f50c',
    storageBucket: 'ustagram-2f50c.firebasestorage.app',
    iosClientId: '411595408555-v85hhidf3o4idjgq7kfu4vic3c27bpnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl89shjKde1qyGZIEtt2BEz0ovtmly9CY',
    appId: '1:411595408555:web:d65b3313e19f48e215e3ee',
    messagingSenderId: '411595408555',
    projectId: 'ustagram-2f50c',
    authDomain: 'ustagram-2f50c.firebaseapp.com',
    storageBucket: 'ustagram-2f50c.firebasestorage.app',
    measurementId: 'G-93VBSR990T',
  );
}
